services:
  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: backend-api
  #   environment:
  #     NODE_ENV: development
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: p@ssword
  #     POSTGRES_DB: mydb
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db

volumes:
  postgres_data: